name: Cypress-test
on:
  push:
    brances:
      - master
      - development
jobs:
  run-next-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - run: npm install
      - run: npm run dev
  run-cypress-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npx cypress run
  