name: Cypress-test
on:
  push:
    brances:
      - master
      - development
jobs:
  test-with-Cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cypress tests
        uses: ./
        with:
          working-directory: /
          build: npx cypress info