name: Cypress-test
on:
  push:
    brances:
      - master
      - development
jobs:
  test-with-Cypress:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2

        run: npm install
        uses: ./
        with:
          working-directory: /
          build: npx cypress info